version: '3'
services:

  #Dropwizard Service
  app:
    build:
      context: .
      dockerfile: ./dropwizard/Dockerfile
    image: dropwizard-service-1:latest
    container_name: app
    restart: unless-stopped
    tty: true
    expose:
      - "8080"
      - "8081"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
      - ./Nginx_config/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx_config/nginx.conf_2:/etc/nginx/conf.d/default.conf
    tty: true
    ports:
      - "80:80"
